### ISSUE TITLE
:recycle:  Button interaction can be upgrade for better accessibility

### ISSUE THREAD

**Issue by mahabubx7** [mnaibei/portfolio#11]
### :recycle:  Button interaction can be upgraded for better accessibility

:arrow_right_hook:  you can update your buttons or link element interaction better with cursor type changes on hover.

As example,
```css
a:hover,
button:hover {
 cursor: pointer;
}
```
